# Generated by Django 5.0.4 on 2026-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='risk',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
